#! /bin/sh

echo "Concatenate files:"

cat configure.in.tmpl > configure.in
cat libmpeg2/configure.incl >> configure.in
cat video/configure.incl >> configure.in

cat <<EOF >>configure.in
dnl
dnl Output configuration files
dnl
AC_SUBST(all_includes)
AC_SUBST(all_libraries)

AC_OUTPUT([     drivers/Makefile.am \
		include/Makefile \
		libmpeg2/Makefile \
		src/Makefile \
		test/Makefile \
		video/Makefile ])
EOF

echo " to configure.in."




set -x
aclocal -I autotools
libtoolize --force --copy
autoheader
automake --add-missing --copy
autoconf
rm -f config.cache
